.\" See LICENSE file for copyright and license details.
.Dd August 19, 2023
.Dt DWM 1
.Os dwm @VERSION@
.Sh NAME
.Nm dwm
.Nd dynamic window manager for X
.Sh SYNOPSIS
.Nm
.Op Fl v
.Sh DESCRIPTION
.Nm
is a dynamic window manager for X.  It manages windows in tiled,
monocle bottom stack, bottom stack horizontal and floating layouts.
Either layout can be applied dynamically, optimising the environment
for the application in use and the task performed.
.Pp
In tiled layouts windows are managed in a master and stacking area.
The master area contains the window which currently needs most
attention, whereas the stacking area contains all other windows.
.Bd -literal -offset indent
tile          ([]=)
+---------+-------+     Tiled layout is selected by default.
|         |   2   |     Also, it can be selected manually by
|         |       |     Meta-t.
|    1    +-------+
|         |   3   |
|         |       |
+---------+-------+
 master    stacking
  area       area
.Ed
.Pp
Gapless grid layout arranges the windows in a grid.
.Bd -literal -offset indent
gaplessgrid   (###)
+-----+-----+-----+     NO MASTER AREA!
|     |     |     |
|  1  |  3  |  5  |     Layout can be selected by Meta-g
|     |     +-----+
|     |     |     |
+-----+-----|  6  |
|     |     +-----+
|  2  |  4  |     |
|     |     |  7  |
+-----+-----+-----+
.Ed
.Pp
In monocle layout all windows are maximised to the screen size.
.Bd -literal -offset indent
monocle       ([M])
+-----------------+     NO MASTER AREA!
|                 |
|                 |     Layout can be selected by Meta-m
|   1/2/3/4...    |
|                 |
|                 |
+-----------------+
.Ed
.Pp
Bottom stack (TTT) and bottom stack horizontal (===) are two
stack layouts for dwm.
.Bd -literal -offset indent
bstack        (TTT)                 bstackhoriz   (===)
+-----------------+                 +-----------------+
|                 |     master      |                 |
|        1        |   <- area ->    |        1        |
|                 |                 |                 |
+-----+-----+-----+                 +-----------------+
|  2  |  3  |  4  |    stacking     +--------2--------+
|     |     |     |   <- area ->    +--------3--------+
+-----+-----+-----+                 +--------4--------+
.Ed
.Pp
In floating layout windows can be resized and moved freely.  Dialog
windows are always managed floating, regardless of the layout applied.
.Pp
Windows are grouped by tags.  Each window can be tagged with one or
multiple tags.  Selecting certain tags displays all windows with these
tags.
.Pp
Each screen contains a small status bar which displays all used tags,
the layout, the title (if compiled with WIN_TITLE) of the focused
window, and the text read from the root window name property, if the
screen is focused.
.Pp
A floating window is indicated with an empty square and a maximised
floating window is indicated with a filled square before the windows
title.
.Pp
The selected tags are indicated with a different color.  The tags of
the focused window are indicated with a filled square in the top left
corner.  The tags which are applied to one or more windows are
indicated with an empty square in the top left corner.
.Pp
dwm draws a small border around windows to indicate the focus state.
.Sh OPTIONS
.Bl -tag -width X
.It Fl v
Print version and exit.
.El
.Sh USAGE
.Ss Status bar
.Bl -tag
.It X root window name
Is read and displayed in the status text area.  It can be set with the
.Xr xsetroot 1
command.
.It Button1
Click on a tag label to display all windows with that tag, click on
the layout label toggles between tiled and floating layout.
.It Button3
Click on a tag label adds/removes all windows with that tag to/from
the view.
.It Meta\-Button1
Click on a tag label applies that tag to the focused window.
.It Meta\-Button3
Click on a tag label adds/removes that tag to/from the focused window.
.El
.SS Keyboard commands
.Bl -tag
.It Meta\-Shift\-Return
Start terminal emulator (defined in
.Pa config.h ).
.It Meta\-,
Focus previous screen, if any.
.It Meta\-.
Focus next screen, if any.
.It Meta\-Shift\-,
Send focused window to previous screen, if any.
.It Meta\-Shift\-.
Send focused window to next screen, if any.
.It Meta\-b
Toggles bar on and off.
.It Meta\-t
Sets tiled layout.
.It Meta\-f
Sets floating layout.
.It Meta\-m
Sets monocle layout.
.It Meta\-s
Sets bstack layout.
.It Meta\-h
Sets bstackhoriz layout.
.It Meta\-space
Toggles between current and previous layout.
.It Meta\-j
Focus next window.
.It Meta\-k
Focus previous window.
.It Meta\-i
Increase clients in master area.
.It Meta\-d
Decrease clients in master area.
.It Meta\-l
Increase master area size.
.It Meta\-h
Decrease master area size.
.It Meta\-Return
Zooms/cycles focused window to/from master area (tiled layouts only).
.It Meta\-n
Set current tag name (
.Xr dmenu 1
required).
.It Meta\-c
Close focused window.
.It Meta\-Shift\-space
Toggle focused window between tiled and floating state.
.It Meta\-Shift\-f
Toggle focused window between fullscreen and tiled state. 
.It Meta\-Tab
Toggles to the previously selected tags.
.It Meta\-Shift\-[1..n]
Apply nth tag to focused window.
.It Meta\-Shift\-0
Apply all tags to focused window.
.It Meta\-Control\-Shift\-[1..n]
Add/remove nth tag to/from focused window.
.It Meta\-[1..n]
View all windows with nth tag.
.It Meta\-0
View all windows with any tag.
.It Meta\-o
Jump on the selected window in the "all windows with any tag" view.
.It Meta\-Control\-[1..n]
Add/remove all windows with nth tag to/from the view.
.It Meta\-Shift\-q
Quit dwm.
.It Meta\-Control\-Shift\-q
Restart dwm.
.El
.SS Mouse commands
.Bl -tag
.It Meta\-Button1
Move focused window while dragging.  Tiled windows will be toggled to
the floating state.
.It Meta\-Button2
Toggles focused window between floating and tiled state.
.It Meta\-Button3
Resize focused window while dragging.  Tiled windows will be toggled
to the floating state.
.El
.Sh CUSTOMIZATION
.Nm
is customized by creating a custom
.Pa config.h
and (re)compiling the source code.
This keeps it fast, secure and simple.
.Sh SIGNALS
.Bl -tag -width XXXXXXXXXXXX
.It SIGHUP - 1
Restart the dwm process.
.It SIGTERM - 15
Cleanly terminate the dwm process.
.El
.Sh SEE ALSO
.Xr dmenu 1
.Sh BUGS
Java applications which use the XToolkit/XAWT backend may draw grey
windows only.  The XToolkit/XAWT backend breaks ICCCM-compliance in
recent JDK 1.5 and early JDK 1.6 versions, because it assumes a
reparenting window manager.  Possible workarounds are using JDK 1.4
(which doesn't contain the XToolkit/XAWT backend) or setting the
environment variable
.Ev AWT_TOOLKIT
to
.Dq \&MToolkit
(to use the older Motif backend instead) or running one of the
following commands:
.Bd -literal -offset indent
1. xprop -root -f _NET_WM_NAME 32a -set _NET_WM_NAME LG3D
2. wmname LG3D
.Ed
(to pretend that a non-reparenting window manager is running that the
XToolkit/XAWT backend can recognize) or when using OpenJDK setting the
environment variable
.Ev _JAVA_AWT_WM_NONREPARENTING
to
.Ql 1 .
.Pp
GTK 2.10.9+ versions contain a broken
.Dq \&Save\-As
file dialog implementation, which requests to reconfigure its window
size in an endless loop.  However, its window is still respondable
during this state, so you can simply ignore the flicker until a new
GTK version appears, which will fix this bug, approximately GTK
2.10.12+ versions.
